name: eshop
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.0
  http: ^0.13.0
  shared_preferences: ^2.0.5
  connectivity: ^3.0.6
  jaguar_jwt: ^3.0.0
  flutter_local_notifications: ^8.2.0
  path_provider: ^2.0.3
  firebase_messaging: ^10.0.7
  cached_network_image: ^3.0.0
  flutter_rating_bar: ^4.0.0
  flutter_html: ^2.1.2
  photo_view: ^0.12.0
  flutter_webview_plugin: ^0.4.0
  firebase_auth: ^3.1.1
  sms_autofill: ^2.0.1
  intl: 0.17.0
  country_code_picker: ^2.0.1
  google_maps_flutter: ^2.0.8
  geolocator: ^7.0.1
  file_picker: ^4.0.2
  shimmer: ^2.0.0
  geocoding: ^2.0.1
  razorpay_flutter: ^1.2.5
  curved_navigation_bar: ^1.0.1
  flutter_paystack: ^1.0.5
  flutter_html_to_pdf: ^0.6.0
  permission_handler: ^8.1.6
  in_app_review: ^2.0.2
  firebase_dynamic_links: ^2.0.9
  open_file: ^3.0.3
  provider: ^6.0.0
  stripe_payment: ^1.1.4
    #^1.0.11
  video_player: ^2.1.5
  flutter_svg: ^0.22.0
  paytm: ^3.0.0
  youtube_player_flutter: ^8.0.0
  share: ^2.0.4
  package_info: ^2.0.2
  url_launcher: ^6.0.3
  version: ^2.0.0
  flutter_downloader: ^1.6.1
  #pay: ^1.0.5
  speech_to_text: ^5.1.0
  downloads_path_provider_28:
    path: ./downloads_path_provider

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - lib/Language/



  fonts:
    - family: opensans
      fonts:
        - asset: assets/font/OpenSans-Regular.ttf
